root: true
env:
  browser: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  curly: warn
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-blocks:
    - warn
    - functions: always
plugins:
  - svelte3
overrides:
  - files:
    - '**/*.svelte'
    processor: svelte3/svelte3
    rules:
      import/first: 0
      import/no-duplicates: 0
      import/no-mutable-exports: 0
